### ISSUE TITLE
Hot take: the Clock Divider is actually an eight step sequencer with a fixed pattern

### ISSUE THREAD

**Issue by McMxxCiV** [JerrySievert/SynthKit#16]
Hi,

I know there's been a discussion about the Clock Divider before, and Jerry then brought on test results to prove the module works as it should. However, the test results showed that output 3 was not active on the ninth clock input, which is actually exactly what the person raising the issue meant. On the n-th clock, every divisor of n should be active. So on the 9th clock, 1 and 3 should be active, then on the 10th clock, 1, 2 and 5 should be active, etc. That's what a clock divider does.

What the test results demonstrated is that the Clock Divider module is actually more like an eight step, eight channel trigger sequencer with a fixed pattern that repeats every 8 steps. Which could be fun, but maybe, for clarity's sake, should get a different name.

Kind regards,
M

**Comment by JerrySievert** [comment]
it is a clock divider, as is the hardware clock divider(s) that its is based on.  not going to change the name because you seem to misunderstand what a clock divider is.

I'd recommend checking out 4ms as a good hardware clock divider manufacturer - I have their clock dividers in hardware, and they behave the same.

**Comment by McMxxCiV** [comment]
To be honest, I think it is you who doesn't understand what a clock divider is. A clock divider divides an incoming clock. It divides it, for instance, in two, where every second incoming clock pulse results in an outgoing clock pulse, or in three, where every third incoming clock pulse results in an outgoing clock pulse. I actually own a hardware 4MS clock divider, and that is what it does.

Yours is indeed a clock divider as long as you only look at the division by 1, 2, 4 and 8: every incoming pulse generates an outgoing pulse at output 1, every second incoming pulse generates an outgoing pulse at output 2, and the same goes for every 4th incoming pulse at ouput 4 and every 8th incoming pulse at output 8.

However, a clock divider like 4MS's or any other hardware clock divider also does this for numbers like 3, 5, 6 and 7, where every third, fifth, sixth and seventh incoming pulse generates an outgoing pulse at outputs 3, 5, 6 and 7 respectively.

Yours does not divide the clock into 3, 5, 6 or 7. It outputs a sequence of eight beats in which 5, 6 and 7 get an output only once, and 3 only twice. With the outputs yours has, it should only repeat after 840 pulses of the incoming clock, as that is the lowest common multiple of all eight outputs.

Do check the 4MS clock divider's outputs. You'll get a pulse at output 3 on the 1st, 4th, 7th, 10th, 13th, etc, incoming pulse. Not at the 3rd, 6th, 11th, 14th, 19th, 22nd etc. like yours does.

**Comment by JerrySievert** [comment]
your opinion is noted, and rejected.
