### ISSUE TITLE
Clock Divider

### ISSUE THREAD

**Issue by McMxxCiV** [JerrySievert/SynthKit#17]
Look, I get that you have a certain idea of what a clock divider is, but could you maybe be open-minded and consider the possibility that you might be wrong? Because what I just formulated wasn't an opinion, it is based on what an actual clock divider right here in front of me is doing: dividing clocks. So you can choose to feel like you're right and reject what I'm saying, or you can make an effort to understand what I'm saying and become even better as a module creator. Because I'm telling you, in this case you're factually wrong, and there's nothing bad about being wrong, because that's how you learn. Except if you just refuse to see you're wrong.

Have a look at this overview. https://www.keithmcmillen.com/blog/simple-synthesis-part-13-clock-division/

**Comment by JerrySievert** [comment]
tell you what, I'll refund the money you paid for synthkit.
